#!/bin/sh

PS1='\[\e[32;40m\]\u@\H[\W]\$\[\e[0m\] '
PS2='> '
PS3='>> '
PS4='+ '
#BLACK='\E[1;30m' BLUE='\e[1;34m' CYAN='\e[1;36m' GREEN='\E[1;32m'
#MAGENTA='\E[1;35m' RED='\e[1;31m' WHITE='\E[1;37m' YELLOW='\E[1;33m'

case $TERM in
    xterm*)
        PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'
        export TERM=xterm
        ;;
    *)
        ;;
esac

# do not override history from several instances
# but append it
shopt -s histappend
export HISTCONTROL="ignoreboth:erasedups"
export HISTSIZE="16384" # commands to remember
export HISTFILESIZE="65535" # lines to remember
# remove duplicates
export HISTIGNORE="&:ls:[bf]g:exit"
# do not break long commands into several lines
shopt -s cmdhist

function rmd { rm -fr $@; }
function rmlog { rm -f *.log; }
function e { ${EDITOR} $@; }
function dmsg { dmesg | $PAGER; }
function ff { find . -type f -iname '*'$*'*' -ls; }
function rmorigrej { find . -type f -name \*.rej -exec rm {} \; ; find . -type f -name \*.orig -exec rm {} \; ; }
function swap
{
    local TMPFILE=tmp.$$;
    mv "$1" $TMPFILE;
    mv "$2" "$1";
    mv $TMPFILE "$2";
}

function hgrep ()
{
    find . -type f -name \*.h -o -name \*.H -o -name \*.hpp| xargs /usr/bin/grep -a --color=auto "$@" /dev/null
}
function strgrep ()
{
    find . -type f -name \*.h -o -name \*.H -o -name \*.hpp -o -name \*.c -o -name \*.cc -o -name \*.cpp -o -name \*.cxx| LC_ALL=C xargs /usr/bin/grep -a --color=auto "`echo $@ | iconv -t cp866`" /dev/null
}
function srcgrep ()
{
    find . -type f -name \*.h -o -name \*.H -o -name \*.hpp -o -name \*.c -o -name \*.cc -o -name \*.cpp -o -name \*.cxx | xargs /usr/bin/grep -a --color=auto "$@" /dev/null
}
function jgrep () 
{
    find . -type f -name \*.java | xargs /usr/bin/grep -a --color=auto "$@" /dev/null
}
function sqlgrep ()
{
    find . -type f -name \*.sql | xargs /usr/bin/grep -a --color=auto "$@" /dev/null
}
function tsgrep ()
{
    find . -type f -name \*.ts | xargs /usr/bin/grep -a --color=auto "$@" /dev/null
}

# aliases
alias ..='cd ..'
alias cd..='cd ..'
alias Ctags='ctags -R --c++-kinds=+p --langmap=c:.c.pc,c++:.c++.cc.cpp.cxx.h.h++.hh.hp.hpp.hxx.C.H.pcc --fields=+ianS  --extra=+q .'
alias cal='cal -m'
alias df='df -kTh'
alias du='du -khs'
alias fortune='fortune -a'
alias lk='ls -lSr'
alias lr='ls -lR'
alias ll='ls -l'
alias ls='ls -hF --color=auto'
alias lx='ls -lXB'
alias tree='tree -Csu'
alias tra='sdcv'
if which rlwrap &> /dev/null; then
    alias telnet='rlwrap telnet'
    alias guile='rlwrap guile'
    alias gdb='rlwrap gdb'
    alias sqlplus='rlwrap sqlplus'
fi
alias grep='grep --color=auto'

# colors for less as MANPAGER
export MANPAGER=less
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;32;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[32;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;32;5;146m' # begin underline

export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig
export PATH="$HOME/bin:$PATH"

declare -x PAGER='less'
declare -x GREP_COLOR='1;32'

if which vim &> /dev/null; then
    declare -x EDITOR='vim'
elif which elvis &> /dev/null; then
    declare -x EDITOR='elvis'
else
    declare -x EDITOR='vi'
fi

declare -x VISUAL="${EDITOR}"
declare -x FCEDIT="${EDITOR}"

if  [ -f ~/.local_sh ]  ; then
    . ~/.local_sh
fi
if [ -f ~/.dir_colors ]; then
    eval `dircolors ~/.dir_colors`
fi
